name: happy_paws
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.12
  flutter_screenutil: ^5.0.1
  google_maps_flutter: ^2.1.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4
  fluttertoast: ^8.0.8
  telephony: ^0.1.4





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  ios: true
  android: true
  image_path_ios: "images/launcher/launcher_icon.png"
  image_path_android: "images/launcher/launcher_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/launcher/background.png"


flutter:


  uses-material-design: true


  assets:
    - mapStyle/map_style.json
    - images/
    - images/intro/
    - images/doc/
    - images/user/
    - images/mapIcons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Shadows Into Light
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf

    - family: Sora
      fonts:
        - asset: fonts/Sora-VariableFont_wght.ttf
